import { LinodeInstancesClient } from './instances';
import { LinodeVolumesClient } from './volumes';
import { LinodeNetworkingClient } from './networking';
import { LinodeNodeBalancersClient } from './nodebalancers';
import { LinodeRegionsClient } from './regions';
import { PlacementClient } from './placement';
import { VPCsClient } from './vpcs';
import { ObjectStorageClient } from './objectStorage';
import { DomainsClient } from './domains';
import { DatabasesClient } from './databases';
import { KubernetesClient } from './kubernetes';
import { ImagesClient } from './images';
import { StackScriptsClient } from './stackScripts';
import { TagsClient } from './tags';
import { SupportClient } from './support';
import { LongviewClientInterface } from './longview';
import { ProfileClientInterface } from './profile';
import { AccountClientInterface } from './account';

export * from './instances';
export * from './volumes';
export * from './networking';
export * from './nodebalancers';
export * from './regions';
export * from './placement';
export * from './vpcs';
export * from './objectStorage';
export * from './domains';
export * from './databases';
export * from './kubernetes';
export * from './images';
export * from './stackScripts';
export * from './tags';
export * from './support';
export * from './longview';
export * from './profile';
export * from './account';

export interface LinodeClient {
  instances: LinodeInstancesClient;
  volumes: LinodeVolumesClient;
  networking: LinodeNetworkingClient;
  nodeBalancers: LinodeNodeBalancersClient;
  regions: LinodeRegionsClient;
  placement: PlacementClient;
  vpcs: VPCsClient;
  objectStorage: ObjectStorageClient;
  domains: DomainsClient;
  databases: DatabasesClient;
  kubernetes: KubernetesClient;
  images: ImagesClient;
  stackScripts: StackScriptsClient;
  tags: TagsClient;
  support: SupportClient;
  longview: LongviewClientInterface;
  profile: ProfileClientInterface;
  account: AccountClientInterface;
}